/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorswing;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author Serhiy
 */
public class Calc extends javax.swing.JFrame {

    Calculating c = new Calculating();
    /**
     * Creates new form Callc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addButtons();
        jPanel1.setLayout(new java.awt.GridLayout(3, 4));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
                
            }
        });
    }
    public void addButtons()
    {
        JButton btnPlus = new JButton("+");
        JButton btnMinus = new JButton("-");
        JButton btnMult = new JButton("*");
        JButton btnDiv = new JButton("/");
        JButton btnEquals = new JButton("=");
        JButton btnClear = new JButton("C");
        for(int i = 0;i<10;++i){
            JButton btn = new JButton(String.valueOf(i));
            btn.addMouseListener(new ExtendMouseAdapter(i));
            jPanel1.add(btn);
        }
        btnPlus.addMouseListener(new OperationMouseAdapter("+"));
        btnMinus.addMouseListener(new OperationMouseAdapter("-"));
        btnMult.addMouseListener(new OperationMouseAdapter("*"));
        btnDiv.addMouseListener(new OperationMouseAdapter("/"));
        btnEquals.addMouseListener(new OperationMouseAdapter("="));
        btnClear.addMouseListener(new OperationMouseAdapter("C"));
        jPanel1.add(btnPlus);
        jPanel1.add(btnMinus);
        jPanel1.add(btnMult);
        jPanel1.add(btnDiv);
        jPanel1.add(btnEquals);
        jPanel1.add(btnClear);
    }
    
   private void plusBtnClick(){
       if(!"".equals(jTextField1.getText())){
            c.a = Integer.parseInt(jTextField1.getText());
            c.operator = "+";
            jTextField1.setText(jTextField1.getText() + c.operator);
            jTextField2.setText(jTextField1.getText());
            jTextField1.setText("");
        
       }
       else{
           jTextField1.setText("");
       }
        
    }
    private void minusBtnClick(){
        
        if(!"".equals(jTextField1.getText())){
        c.a = Integer.parseInt(jTextField1.getText());
        c.operator = "-";
        jTextField1.setText(jTextField1.getText() + c.operator);
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
        }
        else{
            jTextField1.setText("");
        }
    }
    private void multiBtnClick(){
        if(!"".equals(jTextField1.getText())){
        c.a = Integer.parseInt(jTextField1.getText());
        c.operator = "*";
        jTextField1.setText(jTextField1.getText() + c.operator);
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
        }else{
           jTextField1.setText(""); 
        }
    }
    private void divBtnClick(){
        if(!"".equals(jTextField1.getText())){
        c.a = Integer.parseInt(jTextField1.getText());
        c.operator = "/";
        jTextField1.setText(jTextField1.getText() + c.operator);
        jTextField2.setText(jTextField1.getText());
        jTextField1.setText("");
        }else{
            jTextField1.setText(""); 
        }
    }
    private void equalBtnClick(){
        if(c.a != 0){
            c.b = Integer.parseInt(jTextField1.getText());
            c.calculate();
            jTextField2.setText(jTextField2.getText() + c.b);
            jTextField1.setText("");
            jTextField1.setText(String.valueOf(c.res));
        }else{
            jTextField1.setText(""); 
        }
        
    }
    private void clearBtnClick(){
        c.a = 0;
        c.b = 0;
        c.res = 0;
        jTextField1.setText("");
        jTextField2.setText("");
    }
    private void test(String s){
        
        jTextField1.setText(jTextField1.getText() + s);
    }
    class ExtendMouseAdapter extends MouseAdapter{
        
        final int value;
        
        public ExtendMouseAdapter(int x) {
            this.value = x;
        }
        public int getValue()
        {
            return value;
        }
        @Override
        public void mouseClicked(MouseEvent e) 
        {
            test(String.valueOf(value));
        }
    }
    class OperationMouseAdapter extends MouseAdapter{
        final String value;
        
        public OperationMouseAdapter(String x) {
            this.value = x;
        }
        public String getValue()
        {
            return value;
        }
        @Override
        public void mouseClicked(MouseEvent e) 
        {
            
            switch(value){
                case "+": plusBtnClick();
                    break;
                case "-": minusBtnClick();
                    break;
                case "/": divBtnClick();
                    break;
                case "*": multiBtnClick();
                    break;
                case "C": clearBtnClick();
                    break;
                case "=": equalBtnClick();
                    break;
                default:test(value);
                    break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
