/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingmodellesson;

import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyAdapter;
import java.util.LinkedList;
import javax.swing.AbstractListModel;

/**
 *
 * @author Serhiy
 */
public class MainFrame extends javax.swing.JFrame {
 private LocalListModel listModel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        listModel = new LocalListModel();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        textField.addKeyListener(new LokalKeyAdapter());
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        list.addKeyListener(new ListKeyAdapter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setToolTipText("");

        list.setModel(listModel);
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    class LocalListModel extends AbstractListModel{

        private java.util.List<String> strings = new LinkedList<>();
        
        @Override
        public int getSize() {
            return this.strings.size();
        }

        @Override
        public Object getElementAt(int index) {
            return strings.get(index);
        }
        public boolean add(String s){
            int oldLast = strings.size();
            boolean added = strings.add(s);
            this.fireIntervalAdded(this, oldLast, strings.size() - 1);
            return added;
        }
        public void remove(int index){
            int oldLast = strings.size();
            strings.remove(index);
            this.fireIntervalRemoved(this, oldLast, strings.size());
        }
        
    }
    class LokalKeyAdapter extends KeyAdapter{
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt){
            //System.out.println(evt.getKeyCode() + " " + KeyEvent.VK_BACKSPACE);
            switch(evt.getKeyCode()){
                case KeyEvent.VK_ENTER: addItem(); 
                break;
                
            }
        }
    }
    class ListKeyAdapter extends KeyAdapter{
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt){
            //System.out.println(evt.getKeyCode() + " " + KeyEvent.VK_BACKSPACE);
            switch(evt.getKeyCode()){
                
                case KeyEvent.VK_BACKSPACE:System.out.println("backspace"); removeItem();
                break;
            }
        }
    }
    private void addItem(){
		String str = textField.getText();
		textField.requestFocus();
		if(str.length() == 0){
			//
			return;
		} 
		listModel.add(str);
		textField.setText("");
	}
    private void removeItem(){
        int index = list.getSelectedIndex();
        listModel.remove(index);
        System.out.println(index);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
